server/src/controller/spots.ctl.ts
server/src/middlewares/authentication.ts
server/src/routes/spots.routes.ts
server/src/service/spots.service.ts
server/src/types/spots.types.ts

#183 장소 상세조회 시 유저가 pick 했는지 여부도 조회하는 기능
변경 사항을 체크해주세요.
- 장소 상세조회 시 isPicked로 현재 사용자가 이 장소를 찜했는지 여부를 응답해준다.
- 비로그인 사용자일 경우 항상 false로 응답

feat: 장소 상세조회에서 찜하기 여부 조회기능 추가

---

client/src/models/post.model.ts
client/src/pages/Mypage.tsx
client/src/pages/ProfileEditPage.tsx

fix: mypage 수정

---

client/src/apis/place.api.ts
client/src/components/map/ScheduleGoogleMap.tsx
client/src/hooks/useScheduleEdit.ts
client/src/models/place.model.ts
client/src/pages/SchedulePage.tsx

변경 사항을 체크해주세요.
- 내가 찜한 장소인지 판단하는 프로퍼티 `isPicked` 추가
- 인자로 전달받는 장소 배열이 빈배열이거나 없을 경우(`undefined`), `createMarker` 함수가 `map`메서드 실행하지 않도록 early return 추가

[refactor]: 일정 페이지 리팩토링/[fix]: 마커 생성하는 함수 버그 해결(createMarkers) 

---

client/src/routes/router.tsx

Close #139
변경 사항을 체크해주세요.
- 인증된 사용자만 접근이 가능한 페이지
- 마이페이지
- 사용자 정보 수정 페이지
- 비밀번호 변경 페이지
- 게시글 작성 페이지
- 일정 등록 페이지
- 일정 상세조회 페이지
- 일정 수정 페이지
- 인증되지 않은 사용자도 접근 가능한 페이지
- 메인 페이지
- 게시글 목록 페이지
- 게시글 상세조회 페이지
- 에러페이지
- 비밀번호 초기화 페이지
- 로그인 페이지
- 회원가입 페이지

refactor: 라우터 경로 접근 제한 라우터로 코드 개선

---

client/src/components/common/Dropdown.tsx
client/src/components/common/postCard.tsx
client/src/components/layout/Header.tsx
client/src/models/post.model.ts
client/src/pages/MainPage.tsx

#28 
변경 사항을 체크해주세요.
헤더 드롭다운 적용 및 수정

feature: 헤더 드롭다운 적용 및 수정

---

client/src/components/common/LikePlaceCard.tsx

#20 
변경 사항을 체크해주세요.
찜한 장소 카드 수정

style: 찜한 장소 카드 수정

---

server/src/constants/message.ts
server/src/controller/likes.ctl.ts
server/src/controller/mypages.ctl.ts
server/src/controller/posts.ctl.ts
server/src/service/journeys.service.ts
server/src/service/likes.service.ts
server/src/service/posts.service.ts
server/src/utils/posts.utils.ts

[refactor]: [ISSUE#203] posts, journeys리팩토링

---

client/src/components/common/Comment.tsx
client/src/components/common/LikePlaceCard.tsx
client/src/components/common/ProfileCard.tsx

style : 카드 CSS 수정

---

client/src/apis/main.api.ts
client/src/apis/place.api.ts
client/src/components/common/LikePlaceCard.tsx
client/src/components/common/PlaceModal.tsx
client/src/constants/queryKey.ts
client/src/hooks/usePlaceDetails.ts
client/src/styles/theme.ts

[feat]: 장소 찜 모달 컴포넌트 구현, 장소 찜 요청 및 삭제 api 구현 

---

server/package.json
server/tsconfig.json

#215 서버 package.json, tsconfig.json 빌드 용 설정 추가
변경 사항을 체크해주세요.
- build 명령어 추가
- production 코드 실행 명령어 추가
- ts-node 설정 추가

deploy: 서버측 package.json, tsconfig.json 빌드용 설정 추가

---

server/src/service/journeys.service.ts
server/src/service/spots.service.ts

#195 일정 등록,수정, 장소 검색 버그
변경 사항을 체크해주세요.
- 일정 등록하고 수정 할 시 썸네일이 제대로 적용되지 않는 버그 수정
- 장소 검색시 결과가 없을 때 간헐적으로 빈 배열이 전송되는 버그 수정

fix: 일정 등록,수정, 장소 검색 버그 수정

---

client/src/components/schedule/PlaceTabs.tsx
client/src/components/schedule/SearchBox.tsx
client/src/hooks/useScheduleEdit.ts
client/src/pages/ScheduleEditPage.tsx
client/src/pages/SchedulePage.tsx

변경 사항을 체크해주세요.
- 일정 수정페이지에서 바로 일정 등록 페이지로 이동할 경우, 지도 중심점 초기화 되지 않는 문제 해결
- 일정 등록 페이지에서 "일정 등록" 버튼 위치 변경
- 일정 수정 페이지에서 "수정 완료" 버튼 위치 변경

[refactor]: 지도 중심점 초기화 되지 않는 문제 해결/[style]: 일정 등록 버튼 위치 수정

---

client/src/components/common/Comment.tsx
client/src/components/common/Dropdown.tsx
client/src/models/comment.model.ts
client/src/models/post.model.ts
client/src/pages/PostDetailPage.tsx
client/src/pages/PostEditPage.tsx
client/src/pages/WritePage.tsx

#219 
변경 사항을 체크해주세요.
댓글 기능 구현
Css 추가 작업 및 연동 추가 작업 필요

feat : 댓글 기능 구현

---

server/src/constants/message.ts
server/src/controller/comments.ctl.ts
server/src/controller/users.ctl.ts
server/src/service/comments.service.ts
server/src/service/users.service.ts

변경 사항을 체크해주세요.
작업한 API 메시지 상수로 변경

refactor: 작업한 API 메시지 상수로 변경

---

client/src/components/common/Comment.tsx
client/src/components/common/PostComment.tsx
client/src/models/comment.model.ts

#220 
변경 사항을 체크해주세요.
포스트 상세보기 댓글 컴포넌트 구현

feature: 포스트 상세보기 댓글 컴포넌트 구현

---

client/src/models/post.model.ts

- createAt을 createdAt으로 수정
변경 사항을 체크해주세요.
- `createAt`을 `createdAt`으로 수정

[refactor]: post 모델 오타 수정

---

client/src/apis/mypage.api.ts
client/src/constants/pagenation.ts
client/src/hooks/useIntersectionObserver.ts
client/src/hooks/useMypage.ts
client/src/models/post.model.ts
client/src/pages/Mypage.tsx

#65 
변경 사항을 체크해주세요.
마이페이지 무한스크롤 구현

feature: 마이페이지 무한스크롤 구현

---

client/src/apis/mypage.api.ts
client/src/hooks/useMypage.ts
client/src/models/post.model.ts

#229 
변경 사항을 체크해주세요.
페이지네이션 모델 컬럼명 수정

fix: 마이페이지 코드 수정

---

client/src/components/common/Comment.tsx

#230 
변경 사항을 체크해주세요.
코멘트 카드 수정

fix: 코멘트 카드 수정

---

client/src/components/common/PostComment.tsx
client/src/components/common/scheduleCard.tsx
client/src/components/layout/Header.tsx
client/src/hooks/useMypage.ts
client/src/models/post.model.ts
client/src/pages/MainPage.tsx
client/src/pages/PostDetailPage.tsx
client/src/pages/PostEditPage.tsx
client/src/pages/PostPage.tsx
client/src/pages/WritePage.tsx

feat : 게시판 수정 페이지 및 상세 페이지 버그 수정 및 글쓰기 탑 버튼 적용

---

client/src/components/common/Comment.tsx
client/src/hooks/useMypage.ts

#231 
변경 사항을 체크해주세요.
마이페이지 무한스크롤 수정 및 코멘트 카드 수정

fix : 마이페이지 무한스크롤 수정 및 코멘트 카드 수정

---

client/src/pages/Mypage.tsx

마이페이지 탭  페이지 요청 수정
변경 사항을 체크해주세요.
마이페이지 탭  페이지 요청 수정

fix : 마이페이지 탭  페이지 요청 수정

---

client/src/components/common/WriteTopBtn.tsx

변경 사항을 체크해주세요.
- 글쓰기 버튼과 top버튼 색상을 서로 변경
- border를 2px로 굵게 설정
- 글쓰기 font-weight: bold로 설정
- top버튼 화살표 아이콘이 가운데로 위치하도록 padding값 조정
- button hover할 때 opacity:1로 설정
- 두 버튼 모두 box-shadow 설정

[style]: 글쓰기 버튼과 top버튼 스타일 수정

---

.github/workflows/aws-be.yml
.github/workflows/aws-fe.yml
.gitignore
client/Dockerfile
client/vite.config.ts
server/Dockerfile
server/src/settings.ts

Close #177
변경 사항을 체크해주세요.
github-action으로 CI-CD 배포 자동화 구축

deploy: github-action으로 CI-CD 배포 자동화 구축

---

client/tsconfig.json

변경 사항을 체크해주세요.
client > tsconfig 옵션 변경

fix: 프론트 빌드 문제 해결

---

client/src/components/common/PostComment.tsx
client/src/components/common/RegionCountrySelector.tsx
client/src/components/common/scheduleCard.tsx
client/src/models/post.model.ts
client/src/pages/PostDetailPage.tsx
client/src/pages/PostEditPage.tsx
client/src/pages/PostPage.tsx
client/src/pages/WritePage.tsx
server/src/controller/comments.ctl.ts

변경 사항을 체크해주세요.
여행 지 클릭 시 패치, css 수정, 전체일정담기 동작, 좋아요 동작, 좋아요 취소, 댓글 수정 및 삭제 아이콘 작성자만 보이게

fix : fetch post page

---

.github/workflows/aws-fe.yml
client/Dockerfile

fix: client port 수정

---

client/Dockerfile

fix: client 도커파일 수정

---

client/src/components/common/MainPostCard.tsx
client/src/components/common/PostComment.tsx
client/src/icons/icons.ts
client/src/pages/PostDetailPage.tsx

#233 
변경 사항을 체크해주세요.
postComment 수정

fix : postComment 수정

---

.github/workflows/aws-fe.yml
client/.gitignore
client/Dockerfile

#244 도메인 SSL 인증 작업
변경 사항을 체크해주세요.
- http-server 에 인증서 추가
- Dockerfile, github action 변경

deploy: client ssl 적용

---

.github/workflows/aws-fe.yml

#244 도메인 SSL 인증 작업 
변경 사항을 체크해주세요.
- pem 파일 경로 수정

deploy: client ssl 설정 수정

---

client/src/apis/auth.api.ts
client/src/apis/main.api.ts
client/src/apis/mypage.api.ts
client/src/apis/place.api.ts
client/src/components/common/Comment.tsx
client/src/components/schedule/SearchBox.tsx
client/src/components/schedule/SelectPlace.tsx
client/src/hooks/useAuth.ts
client/src/hooks/useMypage.ts
client/src/pages/PostDetailPage.tsx
client/src/pages/PostEditPage.tsx
client/src/pages/ScheduleEditPage.tsx
client/src/pages/SchedulePage.tsx
client/src/pages/WritePage.tsx
server/src/config/ormSetting.ts
server/src/controller/comments.ctl.ts
server/src/controller/mypages.ctl.ts
server/src/controller/posts.ctl.ts
server/src/index.ts
server/src/middlewares/authorization.ts
server/src/service/comments.service.ts
server/src/service/users.service.ts

변경 사항을 체크해주세요.
- 마이페이지 무한 스크롤 버그 수정
- status가 404일때, 무조건 페이지는 1, 글 갯수가 무조건 0이라 1===0 때문에 무한 스크롤 요청이 진행됨 -> 404 에러일때 total count가 존재할때만 무한스크롤이 동작되게 수정
- 주석 삭제

[fix]: [ISSUE#225] 무한스크롤 버그 수정 및 주석/console 제거

---

.github/workflows/aws-be.yml
.gitignore
server/src/app.ts
server/src/config/ormSetting.ts
server/src/index.ts

#244 도메인 SSL 인증 작업 
변경 사항을 체크해주세요.
- express에 ssl 인증서 적용

deploy: server ssl 인증서 적용

---

.github/workflows/aws-be.yml

#244 도메인 SSL 인증 작업
변경 사항을 체크해주세요.
- aws.be.yml 파일 포트 수정

deploy: server ssl yml 파일 포트 수정

---

.github/workflows/aws-be.yml
server/Dockerfile

#244 도메인 SSL 인증 작업
변경 사항을 체크해주세요.
- 백엔드 외부 포트 1234 변경

deploy: 서버 클라이언트 포트 변경

---

client/Dockerfile

deploy: 404 에러 수정

---

client/Dockerfile

#253
변경 사항을 체크해주세요.
- http로 돌려서 확인

deploy: http 로 돌리기

---

client/Dockerfile

#253 배포시 새로고침하면 404 에러 나는 것 수정
변경 사항을 체크해주세요.
- 깃허브 secret 변수에 cert chain 추가

deploy: 인증서 chain 추가

---

client/src/pages/PostEditPage.tsx

#258 
변경 사항을 체크해주세요.
게시글 수정 시 일정과 날짜 같이 불러오기

fix : 게시글 수정 시 일정과 날짜 같이 불러오기

---

client/src/components/common/postCard.tsx
client/src/hooks/useAuth.ts
client/src/pages/ProfileEditPage.tsx
client/src/pages/ProfileResetPassword.tsx
client/src/pages/ResetPassword.tsx

#170 
변경 사항을 체크해주세요.
- 포스트 카드 링크 이미지만 하지 않고 전체로 덮음
- 비로그인 유저 비밀번호 변경 후 로그인 페이지 이동으로 수정하고
비로그인 페이지에서 인증 완료 text 가 초록색으로 적용 되지 않아 수정
- 로그인 유저 프로필 수정 페이지에서 비밀번호 변경 버튼이 
form 안에 있는 button 인데  button type 을 따로 안줘서
버튼 클릭시 간혹 form 에 submit 되는 현상이 발생하는 것 같습니다.
비밀번호 변경 버튼에 타입을 명시해 두었습니다.
또한 아무것도 입력하지 않은 상태로 submit 을 날릴시 해당 submit 을 그냥 리턴 처리하는 것이
제대로 동작하지 않는 것을 수정하였고, "변경사항이 없습니다." 라는 alert 창을 띄우도록 변경하였습니다.

bug 사용자 정보 페이지 수정

---

client/src/routes/router.tsx

Close #262 
변경 사항을 체크해주세요.
- 인증 제한 라우터 코드 수정
- 인증되지 않은 사용자가 인증이 필요한 페이지 경로에 접근 시, 커스텀 alert으로 로그인이 필요한 서비스임을 알려주도록 수정

[refactor]: 로그인하지 않은 사용자가 로그인이 필요한 페이지 경로에 접근 시 커스텀 alert창이 보이게 수정

---

client/src/components/common/CategoryCard.tsx
client/src/components/common/Comment.tsx
client/src/components/common/GuidePostCard.tsx
client/src/components/common/MainPostCard.tsx
client/src/components/common/ProfileCard.tsx
client/src/components/common/WriteTopBtn.tsx
client/src/components/common/postCard.tsx
client/src/components/common/scheduleCard.tsx
client/src/pages/Mypage.tsx
client/src/pages/PostDetailPage.tsx
client/src/pages/PostPage.tsx
server/src/controller/mypages.ctl.ts
server/src/service/posts.service.ts

#260 
변경 사항을 체크해주세요.
post card에 css 변경으로 인한 마이페이지, 메인페이지, 일정 css 수정
post data에 관리자 계정 제외한 데이터 전송

[refactor]: post card css 수정 및 post data 변경

---

client/src/pages/PostEditPage.tsx
client/src/pages/WritePage.tsx

#265 
변경 사항을 체크해주세요.
일정 없을 시 게시글 작성 안되게 기능 추가

feat: 일정 없을 시 게시글 작성 안되게 기능 추가

---

client/src/apis/main.api.ts
client/src/components/common/GuidePostCard.tsx
client/src/hooks/useMain.ts
client/src/pages/MainPage.tsx

변경 사항을 체크해주세요.
- 메인페이지 루트립의 추천 루트 api 구현

[feat]: 메인페이지 루트립의 추천루트 api 구현

---

client/src/pages/PostDetailPage.tsx

변경 사항을 체크해주세요.
게시글 상세 페이지 이미지 스타일 수정

style: 게시글 상세 페이지 이미지 스타일 수정

---

client/src/components/common/CategoryCard.tsx
client/src/components/common/MainPostCard.tsx
client/src/components/common/postCard.tsx
client/src/components/common/scheduleCard.tsx
server/src/service/posts.service.ts

[fix]: 추천 api 수정 및 css 수정

---

client/src/constants/queryKey.ts
client/src/hooks/useMain.ts

변경 사항을 체크해주세요.
- 메인페이지 루트립의 추천루트 쿼리키 수정

[fix]: 루트립의 추천루트 쿼리키 수정

---

client/src/components/common/RegionCountrySelector.tsx
client/src/pages/PostDetailPage.tsx
client/src/pages/PostEditPage.tsx
client/src/pages/WritePage.tsx

#274 
변경 사항을 체크해주세요.
반응형 작업 수정

style: 반응형 작업 수정

---

client/src/apis/auth.api.ts
client/src/hooks/useAuth.ts
client/src/pages/ProfileEditPage.tsx

변경 사항을 체크해주세요.
- 회원 탈퇴 구현
- 사이드바 로그아웃 기능 수정

feature : 회원 탈퇴 구현

---

server/src/service/journeys.service.ts

#276 https://github.com/7days-routrip/routrip/issues/276
변경 사항을 체크해주세요.
- journey 객체는 update로 바꾸고 routeId 부분은 null로 변경

fix: 일정이 포스팅에 첨부되어있을 경우 수정이 되지 않는 버그 수정

---

client/src/components/common/MainPostCard.tsx
client/src/components/common/postCard.tsx
server/src/controller/mypages.ctl.ts
server/src/service/mypages.service.ts
server/src/service/posts.service.ts

변경 사항을 체크해주세요.
main css - hover 시 이미지 transition 추가
mypages - 마이페이지 post service 분리

[fix/style] mypages data post 데이터 변경, main css 수정

---

client/src/components/common/scheduleCard.tsx

[fix] : build error 수정

---

client/src/pages/PostDetailPage.tsx
server/src/config/ormSetting.ts
server/src/service/likes.service.ts

fix : 세부 페이지 수정

---

server/src/utils/posts.utils.ts

[bug]: 내 일정 date 버그 수정

---

client/src/pages/PostDetailPage.tsx

style: 반응형 이미지 수정

---

.github/workflows/aws-be.yml
.github/workflows/aws-fe.yml

변경 사항을 체크해주세요.
github action 실행 설정 변경

fix: github action 실행 설정 변경

---

client/src/apis/auth.api.ts
client/src/hooks/useAuth.ts
client/src/pages/ProfileEditPage.tsx

#288 
변경 사항을 체크해주세요.
프로필 이미지 로직 수정
변경되지 않은 항목에 대해선 undefined 를 주었습니다.
```ts
const profileImageUrl = formImage ? await userProfileImage(formImage) : undefined;
const updateNickname = data.nickname ? data.nickname : undefined;
interface profileUpdateProps {
nickname: string | undefined;
profileImg: string | undefined;
}
export const profileUpdate = async (data: profileUpdateProps) => {
try {
const response = await httpClient.patch<authMessageResponse>("/users/me", data);
return response;
} catch (error) {
// 실패
}
};
```

refactor : 프로필 이미지 로직 수정

---

client/src/hooks/useAuth.ts
client/src/pages/JoinPage.tsx
client/src/pages/ProfileEditPage.tsx

#289 
변경 사항을 체크해주세요.
user 이메일체크, 닉네임체크 코드 리팩토링

refactor : user 이메일체크, 닉네임체크 코드 리팩토링

---

client/src/hooks/useAuth.ts

refactor : useAuth 코드 정리

---

client/src/apis/auth.api.ts
client/src/apis/mypage.api.ts

#294 
변경 사항을 체크해주세요.
user, mypage api코드 정리

refactor : user, mypage api코드 정리
